# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set args and environment variables
ARG VITE_API_URI

ENV VITE_API_URI=${VITE_API_URI}

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Make port 5173 available to the world outside this container
EXPOSE 5173

# Run the command
CMD ["npm", "run", "dev"]
